---
jobs:
    main:
        annotations:
            beta.screwdriver.cd/executor: k8s-vm
        image: node:6
        steps:
            - docker_build: docker build --tag test:hello -q .
            - docker_images: docker images
