---
jobs:
    main:
        image: node:6
        steps:
            - docker_build: docker build --tag test:hello -q .
            - docker_images: docker images
    publish:
        image: node:6
        steps:
            - echo: echo hi
        requires: main
