shared:
    image: node:6
jobs:
    A:
        steps:
            - echo: echo hi
        requires: [~commit, ~pr]
    B:
        steps:
            - echo: echo bye
        requires: A
    D:
        steps:
            - echo: echo stuff
        requires: [A,B]
            
